
name: LinkedIn Radar

on:
  schedule:
    - cron: '0 * * * *'  # roda a cada 1 hora
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests

    - name: Executar o bot
      run: |
        python main.py
