name: LinkedIn Bot - busca por filtro

on:
  schedule:
    - cron: '0 * * * *'  # A cada 1 hora
  workflow_dispatch:

jobs:
  linkedin-job:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Rodar bot LinkedIn
        run: python linkedin_bot.py
