name: Alerta LinkedIn por link Google

on:
  schedule:
    - cron: '0 */2 * * *' # a cada 2 horas
  workflow_dispatch:

jobs:
  rodar-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r requisitos.txt

      - name: Rodar linkedin_bot_v2.py
        run: |
          python linkedin_bot_v2.py
